icons_format = "{icon}"

[theme]
theme = "semi-native"
[theme.overrides]
idle_fg = "#ffffff"

[icons]
icons = "awesome"

[[block]]
block = "custom"
format = " yay: $text "
command = "yay -Sy; yay -Qu | wc -l"
# once in 3 hours
interval = 10800

[[block]]
block = "cpu"
format = " CPU: $utilization "


[[block]]
block = "memory"
format= " MEM: $mem_used_percents.eng(2) "
format_alt = " $icon $swap_used_percents.eng(2) (SWP) "

[[block]]
block = "disk_space"
path = "/"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $used.eng(2)/$total.eng(2) "


[[block]]
block = "backlight"
device = "intel_backlight"
format = " bri: $brightness "


[[block]]
block = "net"
format = " $icon  {$signal_strength $ssid| Wired connection} "
format_alt = " $icon  via $device "

[[block]]
block = "battery"
format = " $icon  $percentage "
empty_format = " $icon Empty! "

[[block]]
block = "temperature"
format = " $icon $average avg "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "custom"
command = "sh ~/.config/i3status-rust/scripts/keyboard.sh"
interval = 1
[[block.click]]
button = "left"
cmd = "xkb-switch -n"

[[block]]
block = "custom"
command = "sh ~/.config/i3status-rust/scripts/playerctl.sh"
format = " $text.rot-str(18) "
hide_when_empty = true
interval = 3

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %I:%M %p "
