icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = ""
idle_bg = ""

[icons]
icons = "awesome6"

[[block]]
block = "custom"
command = "sh ~/.config/i3status-rust/scripts/playerctl.sh"
format = " $text.str(max_w:22,rot_interval:0.5) "
hide_when_empty = true
interval = 3

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "custom"
# format = " yay: $text "
# command = "yay -Sy; yay -Qu | wc -l"
# # once in 3 hours
# interval = 10800

[[block]]
block = "cpu"
format = " CPU: $utilization "


# [[bloc<S-D-R>]]
# block = "memory"
# format = " MEM: $mem_used_percents.eng(w:2) "
# format_alt = " $icon $swap_used_percents.eng(w:2) (SWP) "

[[block]]
block = "disk_space"
path = "/"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $used.eng(w:2)/$total.eng(w:2) "


[[block]]
block = "backlight"
device = "intel_backlight"
format = " bri: $brightness "


[[block]]
block = "net"
format = " $icon  {$signal_strength} "
format_alt = " $icon  via $device "

[[block]]
block = "battery"
format = " $icon  $percentage "
full_format = " $icon "
not_charging_format = " $icon  $percentage "
empty_format = " $icon  $percentage "


[[block]]
block = "temperature"
format = " $icon $average avg "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "custom"
command = "sh ~/.config/i3status-rust/scripts/keyboard.sh"
interval = 1
[[block.click]]
button = "left"
cmd = "xkb-switch -n"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %I:%M %p', l:en_US) "
